### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by sentry0501** [thelinhbkhn2014/VnCoreNLP_Wrapper#5]
I try to run with wseg only but it gave me the following error, could you tell me how to fix it? Thks
    rdrsegmenter = py_vncorenlp.VnCoreNLP(annotators=["wseg"], save_dir='./vncore')
  File "/home/v000986/BenBP/benbp/lib/python3.8/site-packages/py_vncorenlp/vncorenlp.py", line 54, in __init__
    javaclass_vncorenlp = autoclass('vn.pipeline.VnCoreNLP')
  File "/home/v000986/BenBP/benbp/lib/python3.8/site-packages/jnius/reflect.py", line 211, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: vn/pipeline/VnCoreNLP java.lang.NoClassDefFoundError

Here my Java:
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

**Comment by sentry0501** [comment]
I fixed it by replace the path in this line https://github.com/thelinhbkhn2014/VnCoreNLP_Wrapper/blob/e1b39969c8ad5d4f35fa14187edec27559020e30/py_vncorenlp/vncorenlp.py#L52 by the absolute path to jar file and it worked!

**Comment by datquocnguyen** [comment]
It should work by using the absolute folder path for `save_dir`.
